$$f(x) * x*2 + e*X + \frac(2){3\sqrt(x)}$$

Taken from:-
https://www.youtube.com/watch?v=kbBi1liIrFg

Create vector

In [151]:
import numpy as np

#create numpy array
a = np.array(([100, 20, 30, 40, 50]))
print(a)

[100  20  30  40  50]


In [152]:
type(a)

numpy.ndarray

In [153]:
#indexing elements in numpy array
print(a[0])

100


In [154]:
print(a[0:2])

[100  20]


In [155]:
print(a[2:4])

[30 40]


In [156]:
#retrieving dimensions of array
a.shape

(5,)

In [157]:
a.shape[0]

5

Create matrix

In [158]:
A = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]])
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [159]:
#find dimensions
A.shape

(4, 4)

In [160]:
A.shape[0]

4

In [161]:
A.shape[1]

4

In [162]:
print(A[2,3])

400


In [163]:
#extract submatrix
B = A[1:3, 1:4]
B

array([[ 20,  30,  40],
       [200, 300, 400]])

In [164]:
#modify elements of array
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [165]:
A[2,1] = 1/3
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,    0,  300,  400],
       [1000, 2000, 3000, 4000]])

Create special matrices

In [166]:
I = np.eye(10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [167]:
#create all 0's from identity matrix
0*I

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [168]:
#create matrix of all zeros
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [169]:
#create matrix of all ones
np.ones([6,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [170]:
#constant matrix
C = np.full([4, 5], 10)
C

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [171]:
10 * np.ones([4,5])

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [172]:
#create random matrix
X = np.random.random([2,2])
X

array([[0.16277783, 0.81784751],
       [0.93878266, 0.79944714]])

In [173]:
#return random number
Z = np.random.random()
Z

0.27936269530464286

In [174]:
#create large matric
X = np.random.random([10000,2])
X

array([[0.57853189, 0.94155025],
       [0.62698483, 0.28471945],
       [0.35540204, 0.51833522],
       ...,
       [0.17099836, 0.24029979],
       [0.13553773, 0.53952184],
       [0.28615806, 0.20635535]])

In [175]:
#compute mean
np.mean(X)

0.498613155980095

In [176]:
#compute standard deviation
np.std(X)

0.2883376648264258

$$Var(X) = E(X^2) - E^2(X) = \int{0}^1 x^2\ dx - \frac{1}{4} = \frac{1}{3} - \frac{1}{4} = \frac{1}{12}$$

In [177]:
np.std(X)**2

0.08313860895755627

In [178]:
1/12

0.08333333333333333

In [179]:
x = .1
y = 1
z = 'numpy'

In [180]:
print(type(x)), print(" "), print(type(y)), print(" "), print(type(z))

<class 'float'>
 
<class 'int'>
 
<class 'str'>


(None, None, None, None, None)

In [181]:
A

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,    0,  300,  400],
       [1000, 2000, 3000, 4000]])

In [182]:
print(type(A))

<class 'numpy.ndarray'>


In [183]:
print(A.dtype)

int64


Matrix operations

In [184]:
#martix addition
A = np.array([[1, 5, 6], [1, 8, 9], [0, -1, 6]])
B = np.array([[4, 8, 4], [1, 0, 5], [6, -8, 4]])

In [185]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [186]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [187]:
#add matrix

In [188]:
C = A + B
C

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9, 10]])

In [189]:
#another way to add matrices
np.add(A,B, dtype=np.float)

array([[ 5., 13., 10.],
       [ 2.,  8., 14.],
       [ 6., -9., 10.]])

In [190]:
#matrix subtraction
C = A-B
print(C)

[[-3 -3  2]
 [ 0  8  4]
 [-6  7  2]]


In [191]:
#another way to subtract matrix
np.subtract(A, B, dtype=float)

array([[-3., -3.,  2.],
       [ 0.,  8.,  4.],
       [-6.,  7.,  2.]])

In [192]:
#matrix multiplication
#pointwise multiplication
C = A * B
C

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 24]])

In [193]:
#another way to multiply
C = np.multiply(A, B, dtype=float)
C

array([[ 4., 40., 24.],
       [ 1.,  0., 45.],
       [ 0.,  8., 24.]])

In [194]:
#matrix division
#pointwise
C = A / B
print(C)

[[0.25  0.625 1.5  ]
 [1.      inf 1.8  ]
 [0.    0.125 1.5  ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [195]:
#another way to divide matrices
np.divide(A, B, dtype=float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 1.5  ]])

In [196]:
#cast as an integar
np.int16(C)

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1]], dtype=int16)

Matrix products

In [197]:
np.matmul(A, B)

array([[ 45, -40,  53],
       [ 66, -64,  80],
       [ 35, -48,  19]])

$$C = AB$$

$$C_{ij} = \sum_{k=l}^N A_{ik}B_{kj}$$

In [198]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [199]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  4]])

In [200]:
#rectangular array
R = np.array([[1, 2, 3, 4], [2, 5, 6, 8], [1, 2, 4, 10]])
R

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  8],
       [ 1,  2,  4, 10]])

In [201]:
#it does not work to multiply R * A
np.matmul(A, R)

array([[ 17,  39,  57, 104],
       [ 26,  60,  87, 158],
       [  4,   7,  18,  52]])

In [202]:
np.matmul(R.transpose(), A)

array([[  3,  20,  30],
       [  7,  48,  69],
       [  9,  59,  96],
       [ 12,  74, 156]])

In [203]:
a = A[:, 0]
a

array([1, 1, 0])

In [204]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [205]:
b = B[:, 0]
b

array([4, 1, 6])

In [206]:
np.matmul(a, b)

5

In [207]:
np.dot(a, b)

5

$$<a,b = a^T b = \sum_{i=1} ^n a_i b_i$$

In [208]:
#obtain the inner product of two matrices
np.inner(a, b)

5

In [209]:
#working with tensors
C = np.tensordot(A, B)
C

array(146)

In [210]:
a = np.arange(60.).reshape(3, 4, 5)
b = np.arange(24.).reshape(4, 3, 2)

In [211]:
np.tensordot(a, b, axes = ([1, 0], [0, 1]))

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [212]:
np.linalg.matrix_power(A, 2)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

In [213]:
np.matmul(A, A)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

$$C = A \otimes B$$

In [214]:
#chronicle product
np.kron(A, B)

array([[  4,   8,   4,  20,  40,  20,  24,  48,  24],
       [  1,   0,   5,   5,   0,  25,   6,   0,  30],
       [  6,  -8,   4,  30, -40,  20,  36, -48,  24],
       [  4,   8,   4,  32,  64,  32,  36,  72,  36],
       [  1,   0,   5,   8,   0,  40,   9,   0,  45],
       [  6,  -8,   4,  48, -64,  32,  54, -72,  36],
       [  0,   0,   0,  -4,  -8,  -4,  24,  48,  24],
       [  0,   0,   0,  -1,   0,  -5,   6,   0,  30],
       [  0,   0,   0,  -6,   8,  -4,  36, -48,  24]])

Matrix Decompositions

Cholesky decomposition

$$A = UU^H$$

In [215]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [216]:
U = np.linalg.cholesky(A)
U

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  2.64575131,  0.        ],
       [ 0.        , -0.37796447,  2.42015348]])

In [217]:
np.matmul(U, U.transpose().conj())

array([[ 1.,  1.,  0.],
       [ 1.,  8., -1.],
       [ 0., -1.,  6.]])

In [218]:
D = np.array([[1, -2j], [2j, 5]])
D

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [219]:
U = np.linalg.cholesky(D)
U

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [220]:
np.matmul(U, U.T.conj())

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [221]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [222]:
A.T

array([[ 1,  1,  0],
       [ 5,  8, -1],
       [ 6,  9,  6]])

QR Decomposition

$$A = QR$$

In [223]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [224]:
np.linalg.qr(A)

(array([[-0.70710678,  0.63960215, -0.30151134],
        [-0.70710678, -0.63960215,  0.30151134],
        [-0.        ,  0.42640143,  0.90453403]]),
 array([[ -1.41421356,  -9.19238816, -10.60660172],
        [  0.        ,  -2.34520788,   0.63960215],
        [  0.        ,   0.        ,   6.33173824]]))

In [225]:
#extract q matrix
Q = np.linalg.qr(A)[0]
Q

array([[-0.70710678,  0.63960215, -0.30151134],
       [-0.70710678, -0.63960215,  0.30151134],
       [-0.        ,  0.42640143,  0.90453403]])

In [226]:
#extract r matrix
R = np.linalg.qr(A)[1]
R

array([[ -1.41421356,  -9.19238816, -10.60660172],
       [  0.        ,  -2.34520788,   0.63960215],
       [  0.        ,   0.        ,   6.33173824]])

In [227]:
np.matmul(Q, R)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 0., -1.,  6.]])

Eigenvalue decomposition (EVD)

$$A = PDP^{-1}$$

In [228]:
np.linalg.eig(A)

(array([0.34454138+0.j        , 7.32772931+2.69350537j,
        7.32772931-2.69350537j]),
 array([[ 0.9940235 +0.j        ,  0.52656174+0.00429702j,
          0.52656174-0.00429702j],
        [-0.10749871+0.j        ,  0.80658014+0.j        ,
          0.80658014-0.j        ],
        [-0.01900796+0.j        , -0.11875577+0.24091455j,
         -0.11875577-0.24091455j]]))

In [229]:
(d, P) = np.linalg.eig(A)
D = np.diag(d)
D

array([[0.34454138+0.j        , 0.        +0.j        ,
        0.        +0.j        ],
       [0.        +0.j        , 7.32772931+2.69350537j,
        0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        7.32772931-2.69350537j]])

In [230]:
P

array([[ 0.9940235 +0.j        ,  0.52656174+0.00429702j,
         0.52656174-0.00429702j],
       [-0.10749871+0.j        ,  0.80658014+0.j        ,
         0.80658014-0.j        ],
       [-0.01900796+0.j        , -0.11875577+0.24091455j,
        -0.11875577-0.24091455j]])

In [231]:
np.real(np.matmul(np.matmul(P, D), np.linalg.inv(P)))

array([[ 1.00000000e+00,  5.00000000e+00,  6.00000000e+00],
       [ 1.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [-5.55111512e-17, -1.00000000e+00,  6.00000000e+00]])

In [232]:
np.linalg.eigvals(A)

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

Singular Value Decomposition (SVD)

$$A = U S V^T$$

In [233]:
np.linalg.svd(A)

(array([[ 0.52419682, -0.12063215,  0.84300983],
        [ 0.80286468, -0.26006138, -0.53644792],
        [ 0.28394717,  0.95802712, -0.03947205]]),
 array([14.9764806 ,  4.53978289,  0.30886909]),
 array([[ 0.0886097 ,  0.58491408,  0.80624056],
        [-0.08385721, -0.80217028,  0.59117747],
        [ 0.99253025, -0.11999315, -0.02203081]]))

In [234]:
(U, s, V) = np.linalg.svd(A)
U

array([[ 0.52419682, -0.12063215,  0.84300983],
       [ 0.80286468, -0.26006138, -0.53644792],
       [ 0.28394717,  0.95802712, -0.03947205]])

In [235]:
s

array([14.9764806 ,  4.53978289,  0.30886909])

In [236]:
V

array([[ 0.0886097 ,  0.58491408,  0.80624056],
       [-0.08385721, -0.80217028,  0.59117747],
       [ 0.99253025, -0.11999315, -0.02203081]])

Matrix Norms

In [237]:
np.linalg.norm(A)

15.652475842498529

In [238]:
np.linalg.cond(A)

48.48811774406207

In [239]:
np.linalg.cond(B)

3.880342782834484

In [240]:
np.linalg.det(A)

21.0

In [241]:
np.linalg.det(B)

336.0

In [242]:
np.linalg.matrix_rank(A)

3

In [243]:
np.linalg.matrix_rank(B)

3

In [150]:
np.linalg.matrix_rank(R)

3

In [244]:
np.linalg.matrix_rank(U)

3

In [245]:
np.trace(A)

15

In [246]:
np.trace(R)

2.572316793848227

In [248]:
np.trace(D)

(15.000000000000004+0j)

In [250]:
R = np.random.random((3,4))
R

array([[0.49954913, 0.28967913, 0.82519611, 0.88899509],
       [0.55400923, 0.67370027, 0.48992106, 0.55508578],
       [0.68017021, 0.08942287, 0.3775572 , 0.27334842]])

In [251]:
np.trace(R)

1.5508066013901436

Solving Equations

$$Ax = B$$

In [252]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [253]:
b = np.random.random((3, 1))
b

array([[0.49341765],
       [0.63038075],
       [0.33984604]])

In [254]:
x1 = np.matmul(np.linalg.inv(A), b)
x1

array([[ 0.21007435],
       [-0.00941712],
       [ 0.05507149]])

In [255]:
x2 = np.linalg.solve(A,b)
x2

array([[ 0.21007435],
       [-0.00941712],
       [ 0.05507149]])

In [257]:
S = np.array([[1, 2], [2, 4]])
S

array([[1, 2],
       [2, 4]])

In [259]:
np.matmul(np.linalg.pinv(S), S)

array([[0.2, 0.4],
       [0.4, 0.8]])